version: "3"
services:
  mysql-test-db:
    image: mysql:5.7
    restart: always
    hostname: mysql-test-db
    environment:
      MYSQL_DATABASE: 'mysql-test-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'testuser123'
    ports:
      - "3306:3306"
    volumes:
      - test_db_vol:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d

volumes:
  test_db_vol: